baseURL = 'https://ZhongruiXie.github.io/'
title = '这个是我的网站哦'
theme = "PaperMod"

[params]
  defaultTheme = "auto" # 支持 "light" | "dark" | "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = true
  [params.homeInfoParams]
    Title = "你好呀！"
    Content = "这里分享一些技术笔记和生活感悟..."
    ShowInHome = true
    ShowInSidebar = false
    Style = "card"
    Image = "/images/logo.jpg"

  [[params.socialIcons]]
    name = "GitHub"
    url = "https://github.com/ZhongruiXie"

[menu]
  [[menu.main]]
    identifier = "archives"
    name = "Archives"
    url = "/archives/"
    weight = 10

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 20